stages:
    - build
    - deploy

build website:
    image: node:18-alpine
    stage: build
    script:
        - cd ui
        - npm i --force
        - npm run build
        - cd build
        - ls
    artifacts:
        paths:
            - ui/build

deploy to s3:
    stage: deploy
    image:
        name: amazon/aws-cli:2.11.2
        entrypoint: [""]
    script:
        - aws --version
        - aws s3 sync ui/build s3://$AWS_S3_BUCKET --delete
        - aws s3 sync api s3://$AWS_S3_BUCKET_API --delete

deploy to ec2:
    stage: deploy
    image: alpine
    before_script:
        - apk add openssh-client
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
    script:
        - ssh -o StrictHostKeyChecking=no ec2-user@13.50.224.237 "ls;"

