stages:
    - build
    - upload
    - deploy

build website:
    image: node:18-alpine
    stage: build
    script:
        - cd ui
        - npm i --force
        - npm run build
        - cd build
        - ls
    artifacts:
        paths:
            - ui/build

deploy to s3:
    stage: upload
    image:
        name: amazon/aws-cli:2.11.2
        entrypoint: [""]
    script:
        - aws --version
        - aws configure set region eu-north-1
        - aws s3 sync ui s3://pullmaster.io-react --delete
        - aws s3 sync api s3://pullmaster-bucket-api --delete

deploy to ec2:
    stage: deploy
    image: alpine
    before_script:
        - apk add openssh-client
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
    script:
        - ssh -o StrictHostKeyChecking=no ec2-user@13.49.102.10 "ls; aws s3 sync s3://pullmaster-bucket-api api; aws s3 sync s3://pullmaster.io-react ui;"
